-- ============================================================================
-- CSC CENTER DATABASE MIGRATION 004: IDEMPOTENT SEED DATA FOR SERVICES
-- Database System: PostgreSQL (Supabase)
-- ============================================================================

INSERT INTO services (
    slug,
    title,
    short_description,
    description,
    category,
    icon,
    featured,
    available,
    estimated_time,
    service_fee,
    documents,
    process_steps,
    notes
) VALUES
-- 1. IDENTITY & PAN
(
    'pan-card-application',
    'PAN Card Application',
    'Assistance for new Permanent Account Number (Form 49A) online applications.',
    'New PAN Card application assistance for individuals, firms, and minors. Includes document verification, digital photo/signature formatting, and physical card delivery guidance.',
    'identity-pan',
    'CreditCard',
    true,
    true,
    '7 - 15 Business Days',
    NULL,
    '["Aadhaar Card (Proof of Identity & Address)", "Proof of Date of Birth (Birth Cert / Class 10 Marksheet)", "Two recent passport size color photographs"]'::jsonb,
    '[{"step": 1, "title": "Select Service", "description": "Choose PAN Card Application and review mandatory documents."}, {"step": 2, "title": "Submit Information", "description": "Provide applicant personal details and Aadhaar number."}, {"step": 3, "title": "Attach Documents", "description": "Provide clean scanned copies of identity and address proofs."}, {"step": 4, "title": "Center Review", "description": "Operator verifies document compliance with Income Tax rules."}, {"step": 5, "title": "Portal Dispatch", "description": "Application submitted to NSDL/UTIITSL e-governance portal."}, {"step": 6, "title": "Receive e-PAN", "description": "Digital PAN delivered to email; physical card dispatched by post."}]'::jsonb,
    'Ensure the applicant''s name and Date of Birth match exactly with Aadhaar details.'
),
(
    'pan-card-correction',
    'PAN Card Correction',
    'Correction of name, DOB, father''s name, or photo in existing PAN card.',
    'Assistance with updating or correcting existing PAN card details on official NSDL/UTIITSL records. Ensures corrected details match your updated identity documents.',
    'identity-pan',
    'CreditCard',
    false,
    true,
    '10 - 20 Business Days',
    NULL,
    '["Existing PAN Card Copy / PAN Allotment Letter", "Aadhaar Card with updated details", "Gazette Notification or Affidavit (for major name change)"]'::jsonb,
    '[{"step": 1, "title": "Identify Correction", "description": "Specify fields requiring update (Name, DOB, Photo, Signature)."}, {"step": 2, "title": "Provide Supporting Proof", "description": "Supply valid identity proof confirming the corrected details."}, {"step": 3, "title": "Form Verification", "description": "Review correction request form for accuracy."}, {"step": 4, "title": "Portal Submission", "description": "Correction petition filed on official PAN portal."}]'::jsonb,
    'Supporting document must accurately reflect the corrected name or date of birth.'
),
(
    'pan-card-download-assistance',
    'PAN Card Download Assistance',
    'Instant e-PAN PDF download and re-printing service.',
    'Get assistance downloading e-PAN PDF copies from NSDL/UTIITSL portals or re-printing PVC plastic cards.',
    'identity-pan',
    'CreditCard',
    false,
    true,
    'Same Day / Instant',
    NULL,
    '["PAN Number or Application Acknowledgement Number", "Aadhaar Number", "Linked Mobile Phone for OTP validation"]'::jsonb,
    '[{"step": 1, "title": "Provide PAN / Ack No", "description": "Operator looks up e-PAN records."}, {"step": 2, "title": "Authenticate OTP", "description": "Validate via mobile OTP received from portal."}, {"step": 3, "title": "Download PDF", "description": "Print high-resolution color copy or PVC card."}]'::jsonb,
    'Requires mobile number linked to Aadhaar/PAN portal for OTP validation.'
),
(
    'aadhaar-document-assistance',
    'Aadhaar Document Assistance',
    'Guidance for demographic details update, e-Aadhaar download, and UIDAI slot booking.',
    'Comprehensive guidance for Aadhaar document updates (Proof of Identity/Address), e-Aadhaar PDF downloads, PVC Aadhaar order assistance, and UIDAI appointment booking.',
    'identity-pan',
    'Fingerprint',
    true,
    true,
    '3 - 7 Business Days',
    NULL,
    '["Aadhaar Number / Enrolment Slip", "Valid Proof of Address (Electricity bill, Ration card, Passport)", "Mobile phone linked with Aadhaar"]'::jsonb,
    '[{"step": 1, "title": "Review Document List", "description": "Check UIDAI approved document list for valid POI/POA."}, {"step": 2, "title": "Form Preparation", "description": "Prepare update request details accurately."}, {"step": 3, "title": "Portal Guidance", "description": "Assist with myAadhaar portal filing or appointment booking."}]'::jsonb,
    'Actual biometric updates (fingerprint/iris) must be completed at an official UIDAI enrolment center.'
),

-- 2. GOVERNMENT DOCUMENTS
(
    'income-certificate',
    'Income Certificate Assistance',
    'Filing support for state government family annual income certificates.',
    'End-to-end guidance for obtaining state e-District Income Certificates required for educational scholarships, Fee Waiver schemes, and government welfare benefits.',
    'government-documents',
    'FileCheck',
    true,
    true,
    '10 - 21 Business Days',
    NULL,
    '["Aadhaar Card of Applicant / Parent", "Ration Card / Voter ID", "Salary Slip / Form 16 / Income Affidavit", "Land Revenue Receipt / Patta (if applicable)"]'::jsonb,
    '[{"step": 1, "title": "Prepare Income Proof", "description": "Gather salary slips, IT returns, or self-declaration affidavits."}, {"step": 2, "title": "Form Submission", "description": "Fill e-District portal application form with accuracy."}, {"step": 3, "title": "Verification by Authorities", "description": "Local Revenue Inspector / Tehsildar verifies details."}, {"step": 4, "title": "Certificate Download", "description": "Download digitally signed certificate upon approval."}]'::jsonb,
    'Income certificates are generally valid for one financial year.'
),
(
    'residence-certificate',
    'Residence & Domicile Certificate',
    'Assistance for official residence and state domicile proof certificates.',
    'Documentation support for applying for State Domicile and Native Residence Certificates essential for state quota college admissions, government jobs, and housing schemes.',
    'government-documents',
    'FileCheck',
    false,
    true,
    '10 - 15 Business Days',
    NULL,
    '["Applicant Aadhaar Card", "Continuous Residence Proof (Electricity bills / School Leaving Cert)", "Parent''s Residence Proof or Land Document"]'::jsonb,
    '[{"step": 1, "title": "Check Eligibility", "description": "Verify minimum required years of residence in state."}, {"step": 2, "title": "Upload Proofs", "description": "Provide address documents and school records."}, {"step": 3, "title": "E-District Application", "description": "Submit application to state revenue authority."}]'::jsonb,
    'Requirements vary according to state government e-District guidelines.'
),
(
    'caste-certificate',
    'Caste Certificate Assistance',
    'Filing support for SC / ST / OBC / EWS reservation certificates.',
    'Guidance for submitting online applications for Caste and Category Certificates (SC, ST, OBC, EWS) needed for reservation benefits in education and public recruitment.',
    'government-documents',
    'FileCheck',
    false,
    true,
    '15 - 30 Business Days',
    NULL,
    '["Applicant Aadhaar Card", "Blood Relative''s Caste Certificate (Father / Paternal Uncle)", "School Leaving Certificate showing caste entry", "Affidavit on Stamp Paper"]'::jsonb,
    '[{"step": 1, "title": "Gather Family Proof", "description": "Locate existing paternal family caste records."}, {"step": 2, "title": "File e-District Form", "description": "Fill state category certificate application."}, {"step": 3, "title": "Inquiry & Approval", "description": "Revenue department verifies ancestral records."}]'::jsonb,
    'OBC Non-Creamy Layer (NCL) certificates require current year income proof.'
),
(
    'birth-death-certificate',
    'Birth & Death Certificate Services',
    'Application and duplicate download support for Civil Registration System (CRS).',
    'Assistance with online registration guidance, status check, and digital copy downloads for Birth and Death certificates through municipal or CRS portals.',
    'government-documents',
    'FileCheck',
    false,
    true,
    '7 - 15 Business Days',
    NULL,
    '["Hospital Discharge Slip / Institutional Slip", "Parents'' / Informant Aadhaar Cards", "Registration Number (for existing record search)"]'::jsonb,
    '[{"step": 1, "title": "Search CRS Database", "description": "Check availability of record on municipal portal."}, {"step": 2, "title": "File Application", "description": "Submit application for new entry or digital copy."}, {"step": 3, "title": "Download Certificate", "description": "Retrieve QR-verified digital certificate."}]'::jsonb,
    'Late registration beyond 21 days requires permission from designated authorities.'
),

-- 3. EDUCATION
(
    'scholarship-application',
    'Scholarship Application Assistance',
    'Online form filling for National Scholarship Portal (NSP) and State schemes.',
    'Complete assistance for pre-matric, post-matric, higher education, and merit-cum-means scholarship submissions on NSP, State E-Kalyan, and Mahadbt portals.',
    'education',
    'GraduationCap',
    true,
    true,
    'Varies by Scheme Deadline',
    NULL,
    '["Student Aadhaar Card (Linked with Mobile)", "Valid Income Certificate", "Caste / Category Certificate (if applicable)", "Previous Academic Marksheet & Institute Fee Receipt", "Bank Passbook with Aadhaar Seeding"]'::jsonb,
    '[{"step": 1, "title": "Check Portal Deadlines", "description": "Verify scheme opening dates and eligibility cutoff."}, {"step": 2, "title": "Register Student Profile", "description": "Create OTR (One Time Registration) profile."}, {"step": 3, "title": "Upload Marksheets & Fees", "description": "Format and attach clear academic scans."}, {"step": 4, "title": "Institute Verification", "description": "Submit acknowledgement copy to school/college nodal officer."}]'::jsonb,
    'Student bank account must be seeded with Aadhaar for Direct Benefit Transfer (DBT).'
),
(
    'college-admission-forms',
    'College & University Admission Forms',
    'Online registration for BA, BSc, BCom, BTech, and PG admissions.',
    'Guidance and online form filing for central universities (CUET), state college portals, degree admissions, subject choice filling, and counselling registration.',
    'education',
    'BookOpen',
    false,
    true,
    'Immediate Online Submission',
    NULL,
    '["Class 10th and 12th Marksheets", "Transfer / Migration Certificate", "Scanned Photo & Signature", "Category Certificate (for quota reservation)"]'::jsonb,
    '[{"step": 1, "title": "Select Target College", "description": "Review eligibility criteria and cutoff subjects."}, {"step": 2, "title": "Fill Registration Form", "description": "Enter personal, academic, and subject preferences."}, {"step": 3, "title": "Fee Payment & Submit", "description": "Complete application fee payment and print receipt."}]'::jsonb,
    'Double check subject combination preferences prior to final lock.'
),

-- 4. JOBS & EXAMS
(
    'govt-job-application',
    'Government Job Application Assistance',
    'Online recruitment application filing for SSC, UPSC, Railways, Banking, & Defense.',
    'Error-free online application assistance for Staff Selection Commission (SSC), UPSC, IBPS Banking, RRB Railway, Police, and State Public Service Commission vacancies.',
    'jobs-exams',
    'Briefcase',
    true,
    true,
    'Immediate Online Submission',
    NULL,
    '["Educational Certificates & Marksheets (10th/12th/Degree)", "Photo (specific dimensions/background)", "Signature Scan (black/blue ink as required)", "Category / Ex-Serviceman Certificate (if applicable)"]'::jsonb,
    '[{"step": 1, "title": "Verify Notification", "description": "Check eligibility age limit and educational requirement."}, {"step": 2, "title": "Format Photo & Signature", "description": "Resize images to exact KB and pixel specifications."}, {"step": 3, "title": "Submit Form", "description": "Complete form inputs and download exam confirmation PDF."}]'::jsonb,
    'Photographs must be recent with clear face visibility and light background.'
),
(
    'admit-card-result-assistance',
    'Admit Card & Result Download',
    'Fast retrieval and printing of exam hall tickets and official marksheets.',
    'Download and high-quality printout service for recruitment exam admit cards, hall tickets, roll number lookup, and scorecards.',
    'jobs-exams',
    'Briefcase',
    false,
    true,
    'Instant On-Spot',
    NULL,
    '["Registration Number / Application ID", "Date of Birth / Password"]'::jsonb,
    '[{"step": 1, "title": "Provide Credentials", "description": "Enter Roll Number or Registration ID."}, {"step": 2, "title": "Download File", "description": "Retrieve PDF admit card or scorecard."}, {"step": 3, "title": "Print Copy", "description": "Get clear color or B&W printout."}]'::jsonb,
    'Check exam center address and instructions printed on the admit card.'
),

-- 5. FINANCIAL & UTILITY
(
    'electricity-bill-assistance',
    'Electricity Bill Payment Assistance',
    'Instant bill lookup and payment submission for state electricity boards.',
    'Assistance with fetching monthly electricity bills, reviewing consumer account details, and completing online payment submissions with instant digital receipts.',
    'financial-utility',
    'Receipt',
    false,
    true,
    'Instant Real-time Receipt',
    NULL,
    '["Consumer Account Number (CA / K No / Account ID)", "Previous Bill Copy (Optional)"]'::jsonb,
    '[{"step": 1, "title": "Enter Consumer No", "description": "Fetch current due amount from board portal."}, {"step": 2, "title": "Verify Bill Details", "description": "Confirm consumer name and billing period."}, {"step": 3, "title": "Process Payment", "description": "Receive instant printed payment confirmation."}]'::jsonb,
    'Always pay before due date to avoid disconnection penalty charges.'
),
(
    'banking-service-assistance',
    'Banking Service Assistance',
    'Guidance for online account opening forms, PMJDY, and DBT status check.',
    'Guidance for filling online bank account opening forms, checking Direct Benefit Transfer (DBT) linking status, and pension scheme applications.',
    'financial-utility',
    'Receipt',
    false,
    true,
    'Same Day',
    NULL,
    '["Aadhaar Card", "PAN Card", "Passport Photograph", "Mobile Number linked to Aadhaar"]'::jsonb,
    '[{"step": 1, "title": "Form Filing Guidance", "description": "Assist with digital bank account application forms."}, {"step": 2, "title": "DBT Status Check", "description": "Verify if Aadhaar is linked with bank for subsidies."}]'::jsonb,
    'DISCLAIMER: This center is a digital service assistance provider and is NOT a bank or financial institution. Financial transactions are conducted through official banking portals.'
),

-- 6. TRAVEL & PASSPORT
(
    'passport-application-assistance',
    'Passport Application Assistance',
    'Form filling, fee payment, and slot booking for Fresh & Re-issue Passports.',
    'Complete guidance for Passport Seva portal account creation, online application (Form 1), document advisor review, fee payment, and Passport Seva Kendra (PSK) appointment booking.',
    'travel-passport',
    'Globe',
    true,
    true,
    'Appointment as per PSK availability',
    NULL,
    '["Aadhaar Card / Voter ID (Identity & Address Proof)", "Class 10th Certificate (ECNR Proof)", "Bank Passbook with photo / Utility bill"]'::jsonb,
    '[{"step": 1, "title": "Create Passport Seva Account", "description": "Register applicant on official portal."}, {"step": 2, "title": "Fill Form 1", "description": "Provide applicant details, parents'' names, and address."}, {"step": 3, "title": "Pay Official Govt Fee", "description": "Submit ₹1500 (or applicable) fee on portal."}, {"step": 4, "title": "Book PSK Slot", "description": "Select convenient date and time at nearest PSK."}, {"step": 5, "title": "Visit PSK", "description": "Applicant visits PSK with original documents for biometrics."}]'::jsonb,
    'Applicant must physically attend the Passport Seva Kendra appointment with original documents.'
),
(
    'travel-ticket-assistance',
    'Travel Ticket Assistance',
    'Online IRCTC Train, Bus, and Flight ticket booking assistance.',
    'Assistance with searching train availability, booking IRCTC e-tickets, state transport bus reservations, and checking PNR status.',
    'travel-passport',
    'Globe',
    false,
    true,
    'Instant Booking',
    NULL,
    '["Passenger Names, Ages, and Gender", "Valid Identity Card details"]'::jsonb,
    '[{"step": 1, "title": "Search Routes", "description": "Find available train/bus connections."}, {"step": 2, "title": "Book Ticket", "description": "Fill passenger details and complete booking."}, {"step": 3, "title": "Print Ticket", "description": "Receive printed e-ticket with PNR number."}]'::jsonb,
    'Carry original photo ID during travel as mandated by railway/bus authorities.'
),

-- 7. DIGITAL & DOCUMENTATION
(
    'printing-scanning-services',
    'Printing & Scanning Services',
    'High-resolution color/B&W printing, document scanning, and PDF creation.',
    'On-spot high quality printing (Color/B&W), multi-page document scanning, image cleaning, and multi-file PDF compilation for online submissions.',
    'digital-services',
    'Printer',
    false,
    true,
    'Instant On-Spot',
    NULL,
    '["Physical Documents or Soft Copy (Email / USB)"]'::jsonb,
    '[{"step": 1, "title": "Provide File", "description": "Submit document via email or USB drive."}, {"step": 2, "title": "Print / Scan", "description": "Operator executes high resolution print or scan."}]'::jsonb,
    'Confidential handling for all customer documents.'
),
(
    'photo-signature-resize',
    'Photo & Signature Resize Services',
    'Image formatting according to exact exam & portal KB specifications.',
    'Crop, compress, and resize photographs and signatures to match mandatory portal requirements (e.g., 20KB-50KB, specific pixel ratios).',
    'digital-services',
    'Image',
    false,
    true,
    '5 - 10 Minutes',
    NULL,
    '["Scanned Photo or Physical Photograph", "Signature on white paper with black/blue pen"]'::jsonb,
    '[{"step": 1, "title": "Check Portal Specs", "description": "Review required KB size and dimensions."}, {"step": 2, "title": "Process Image", "description": "Resize, crop, and optimize image clarity."}, {"step": 3, "title": "Deliver File", "description": "Save processed file for your application."}]'::jsonb,
    'Avoid blurred signatures or shadowy background photos.'
),
(
    'document-upload-assistance',
    'Document Upload Assistance',
    'Help with uploading multi-page PDFs and compressed files to portals.',
    'Technical assistance for applicants facing difficulties uploading heavy documents, merging multiple certificates into a single PDF, or resolving portal upload errors.',
    'digital-services',
    'Laptop',
    false,
    true,
    'Same Day',
    NULL,
    '["Files requiring upload", "Portal login credentials / application ID"]'::jsonb,
    '[{"step": 1, "title": "Inspect Files", "description": "Check file sizes and formats."}, {"step": 2, "title": "Optimize & Merge", "description": "Combine pages into compressed single PDF if needed."}, {"step": 3, "title": "Upload to Portal", "description": "Assist with successful portal attachment."}]'::jsonb,
    'Ensure file names do not contain special characters.'
),

-- 8. OTHER ONLINE SERVICES
(
    'voter-id-assistance',
    'Voter ID Services',
    'New Voter Registration (Form 6), correction, and e-EPIC download.',
    'Assistance with Election Commission of India (ECI) portal applications for new voter registration, address correction (Form 8), and e-EPIC digital card downloads.',
    'other',
    'Grid',
    false,
    true,
    '15 - 30 Business Days',
    NULL,
    '["Aadhaar Card", "Age Proof (18+ years)", "Current Residence Address Proof", "Passport Photograph"]'::jsonb,
    '[{"step": 1, "title": "Form Selection", "description": "Choose Form 6 (New) or Form 8 (Correction)."}, {"step": 2, "title": "File Application", "description": "Submit details on NVSP portal."}, {"step": 3, "title": "BLO Verification", "description": "Booth Level Officer verifies residence."}]'::jsonb,
    'Applicant must be 18 years or older as of the qualifying date.'
),
(
    'jeevan-pramaan-assistance',
    'Digital Life Certificate (Jeevan Pramaan)',
    'Biometric Digital Life Certificate generation for pensioners.',
    'Assistance for government and defense pensioners in generating biometric Digital Life Certificates (Jeevan Pramaan) online without visiting bank branches.',
    'other',
    'Grid',
    true,
    true,
    'Instant On-Spot',
    NULL,
    '["Aadhaar Number", "Pension Payment Order (PPO) Number", "Bank Account details receiving pension", "Mobile Number for OTP"]'::jsonb,
    '[{"step": 1, "title": "Enter PPO Details", "description": "Input pensioner Aadhaar and PPO number."}, {"step": 2, "title": "Biometric Scan", "description": "Authenticate pensioner fingerprint or face scan."}, {"step": 3, "title": "Generate Certificate", "description": "Instant Pramaan ID generated and sent to pension disbursing agency."}]'::jsonb,
    'Requires physical presence of the pensioner for biometric authentication.'
)

-- Idempotent UPSERT Logic
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    icon = EXCLUDED.icon,
    featured = EXCLUDED.featured,
    available = EXCLUDED.available,
    estimated_time = EXCLUDED.estimated_time,
    service_fee = EXCLUDED.service_fee,
    documents = EXCLUDED.documents,
    process_steps = EXCLUDED.process_steps,
    notes = EXCLUDED.notes,
    updated_at = NOW();
